name: Fork CI

on:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x
      - feat-fork-ci
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
  CARGO_INCREMENTAL: '0'

jobs:
  check_style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup show

      - name: Check Formatting
        run: cargo fmt --all -- --check

  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          ./script/linux

      - name: Install Rust Toolchain
        run: rustup show

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

      - name: Run Tests
        run: cargo nextest run --workspace --all-targets --no-fail-fast --no-tests=warn
